server:
  port: 8002
spring:
  application:
    name: projects
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-ezjh4cma.bj.tencentcdb.com:10210/Defect-Analysis?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abcd1234
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
#开启feign的熔断：默认是线程池隔离
feign:
  hystrix:
    enabled: true
