spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigin: "*" # 允许所有域
            allowedMethods: # 支持方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: gitlab_users_route

          # lb表示使用LoadBalancerClient实现负载均衡，后面goods是微服务的名称[主要应用于集群环境]
          uri: lb://users
          # 路由断言，路由规则配置
          predicates:
            # 路径请求过滤，以/brand开始的请求都路由到uri上去
            - Path=/api/users/**
            #- Path=/**
          filters:
            # 去除path后的第一个斜杠（如/api）
            - StripPrefix=1
            # 自动加前缀/brand
            #- PrefixPath=/brand

            # 局部限流过滤器
            - name: RequestRateLimiter # 请求数限流，名字不能乱写，使用默认的factory
              args:
                # 每秒允许的请求数
                redis-rate-limiter.replenishRate: 1
                # 允许并发数【宽限个数】
                redis-rate-limiter.burstCapacity: 4

        - id: gitlab_projects_route
          uri: lb://projects
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 4
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
